const invoice = {
  ar: {
    invoice: "فاتورة",
    billTo: "فاتورة إلى",
    invoiceDate: "تاريخ الفاتورة",
    dueDate: "تاريخ الاستحقاق",
    description: "الوصف",
    qty: "الكمية",
    unitPrice: "سعر الوحدة",
    amount: "المبلغ",
    subtotal: "المجموع الفرعي",
    tax: "الضريبة",
    discount: "الخصم",
    balanceDue: "المبلغ المستحق",
    paid: "المدفوع",
    notes: "ملاحظات",
    thankYou: "شكراً لتعاملكم معنا!",
  },
  en: {
    invoice: "INVOICE",
    billTo: "BILL TO",
    invoiceDate: "Invoice Date:",
    dueDate: "Due Date:",
    description: "Description",
    qty: "Qty",
    unitPrice: "Unit Price",
    amount: "Amount",
    subtotal: "Subtotal:",
    tax: "Tax:",
    discount: "Discount:",
    balanceDue: "Balance Due:",
    paid: "Paid:",
    notes: "NOTES",
    thankYou: "Thank you for your business!",
  },
};

const examination = {
  ar: {
    examination: "فحص",
    date: "التاريخ:",
    patient: "المريض:",
    vision: "الرؤية وضغط العين",
    rightEyeWithout: "العين اليمنى (بدون تصحيح)",
    rightEyeWith: "العين اليمنى (مع تصحيح)",
    rightEyePressure: "ضغط العين اليمنى",
    leftEyeWithout: "العين اليسرى (بدون تصحيح)",
    leftEyeWith: "العين اليسرى (مع تصحيح)",
    leftEyePressure: "ضغط العين اليسرى",
    corneaLens: "القرنية والعدسة",
    cornealShapeR: "شكل القرنية (يمنى)",
    cornealSurfaceR: "سطح القرنية (يمنى)",
    retinaR: "شبكية العين (يمنى)",
    cataractR: "إعتام عدسة العين (يمنى)",
    lensClarityR: "وضوح العدسة (يمنى)",
    fundusR: "قاع العين (يمنى)",
    cornealShapeL: "شكل القرنية (يسرى)",
    cornealSurfaceL: "سطح القرنية (يسرى)",
    retinaL: "شبكية العين (يسرى)",
    cataractL: "إعتام عدسة العين (يسرى)",
    lensClarityL: "وضوح العدسة (يسرى)",
    fundusL: "قاع العين (يسرى)",
    prescription: "الوصفة الطبية",
    refractionR: "انكسار العين (يمنى)",
    sphericalR: "القوة الكروية (يمنى)",
    cylindricalR: "القوة الأسطوانية (يمنى)",
    axisR: "المحور (يمنى)",
    additionR: "الإضافة للقراءة (يمنى)",
    refractionL: "انكسار العين (يسرى)",
    sphericalL: "القوة الكروية (يسرى)",
    cylindricalL: "القوة الأسطوانية (يسرى)",
    axisL: "المحور (يسرى)",
    additionL: "الإضافة للقراءة (يسرى)",
    contactLenses: "العدسات اللاصقة",
    lensTypeR: "نوع العدسة (يمنى)",
    lensDiameterR: "قطر العدسة (يمنى)",
    baseCurveR: "المنحنى الأساسي (يمنى)",
    lensTypeL: "نوع العدسة (يسرى)",
    lensDiameterL: "قطر العدسة (يسرى)",
    baseCurveL: "المنحنى الأساسي (يسرى)",
    frame: "الإطار",
    frameType: "النوع",
    manufacturer: "المصنع",
    model: "الموديل",
    size: "المقاس",
    material: "المادة",
    color: "اللون",
    shape: "الشكل",
    frameLenses: "عدسات الإطار",
    frameLensType: "نوع العدسة",
    frameLensIndex: "معامل العدسة",
    coating: "الطلاء",
    uvProtection: "الحماية من الأشعة فوق البنفسجية",
    frameLensColor: "اللون",
    prescriptions: "الوصفات والتعليمات",
    eyeglassesRx: "وصفة النظارات",
    contactLensesRx: "وصفة العدسات اللاصقة",
    additionalTreatments: "علاجات إضافية",
    followUp: "تعليمات المتابعة",
    generalNotes: "ملاحظات عامة",
  },
  en: null,
};

const prescription = {
  ar: {
    rx: "وصفة طبية",
    date: "التاريخ:",
    patient: "المريض:",
    doctor: "الطبيب:",
    rightEye: "العين اليمنى",
    leftEye: "العين اليسرى",
    spherical: "القوة الكروية",
    cylindrical: "القوة الأسطوانية",
    axis: "المحور",
    addition: "إضافة للقراءة",
    eyeglasses: "وصفة النظارات",
    contactLenses: "وصفة العدسات اللاصقة",
    lensType: "نوع العدسة",
    baseCurve: "المنحنى الأساسي",
    diameter: "القطر",
    followUp: "تعليمات المتابعة",
    notes: "ملاحظات",
    sign: "التوقيع:",
  },
  en: {
    rx: "PRESCRIPTION",
    date: "Date:",
    patient: "Patient:",
    doctor: "Doctor:",
    rightEye: "Right Eye (OD)",
    leftEye: "Left Eye (OS)",
    spherical: "Spherical",
    cylindrical: "Cylindrical",
    axis: "Axis",
    addition: "Addition (Near)",
    eyeglasses: "Eyeglasses Prescription",
    contactLenses: "Contact Lenses Prescription",
    lensType: "Lens Type",
    baseCurve: "Base Curve",
    diameter: "Diameter",
    followUp: "Follow-up Instructions",
    notes: "Notes",
    sign: "Signature:",
  },
};

const patientSummary = {
  ar: {
    summary: "ملخص المريض",
    patientInfo: "معلومات المريض",
    name: "الاسم",
    displayId: "الرقم المرجعي",
    birthDate: "تاريخ الميلاد",
    gender: "الجنس",
    phone: "الهاتف",
    email: "البريد الإلكتروني",
    address: "العنوان",
    type: "النوع",
    notes: "ملاحظات",
    appointments: "المواعيد الأخيرة",
    examDate: "التاريخ",
    examTime: "الوقت",
    examType: "النوع",
    examStatus: "الحالة",
    examReason: "السبب",
    examinations: "الفحوصات الأخيرة",
    examId: "الرقم",
    examStatusLabel: "الحالة",
    invoices: "الفواتير الأخيرة",
    invId: "الرقم",
    invDate: "التاريخ",
    invStatus: "الحالة",
    invTotal: "الإجمالي",
    invPaid: "المدفوع",
    invRemaining: "المتبقي",
    noData: "لا توجد بيانات",
    male: "ذكر",
    female: "أنثى",
    regular: "عادي",
    vip: "مميز",
  },
  en: {
    summary: "PATIENT SUMMARY",
    patientInfo: "Patient Information",
    name: "Name",
    displayId: "ID",
    birthDate: "Date of Birth",
    gender: "Gender",
    phone: "Phone",
    email: "Email",
    address: "Address",
    type: "Type",
    notes: "Notes",
    appointments: "Recent Appointments",
    examDate: "Date",
    examTime: "Time",
    examType: "Type",
    examStatus: "Status",
    examReason: "Reason",
    examinations: "Recent Examinations",
    examId: "ID",
    examStatusLabel: "Status",
    invoices: "Recent Invoices",
    invId: "ID",
    invDate: "Date",
    invStatus: "Status",
    invTotal: "Total",
    invPaid: "Paid",
    invRemaining: "Remaining",
    noData: "No records",
    male: "Male",
    female: "Female",
    regular: "Regular",
    vip: "VIP",
  },
};

const report = {
  ar: {
    page: "صفحة",
    of: "من",
    signature: "توقيع المسؤول",
    total: "الإجمالي",
  },
  en: {
    page: "Page",
    of: "of",
    signature: "Authorized Signature",
    total: "Total",
  },
};

module.exports = {
  invoice,
  examination,
  prescription,
  patientSummary,
  report,
};
