import type { ExamStatus } from "../enums";
import type { Patient } from "./core";

export interface Examination {
  id: number;
  displayId: string;
  patientId: number;
  patient?: Pick<Patient, "id" | "fullName" | "displayId">;
  examDate: string;
  examStatus: ExamStatus;
  examType?: string;
  rightEyeWithoutCorrection?: string;
  rightEyeWithCorrection?: string;
  rightEyePressure?: string;
  leftEyeWithoutCorrection?: string;
  leftEyeWithCorrection?: string;
  leftEyePressure?: string;
  cornealShapeRightEye?: string;
  cornealSurfaceRightEye?: string;
  rightEyeRetinaExamination?: string;
  presenceOfCataractRightEye?: string;
  lensClarityRightEye?: string;
  rightEyeFundusExamination?: string;
  cornealShapeLeftEye?: string;
  cornealSurfaceLeftEye?: string;
  leftEyeRetinaExamination?: string;
  presenceOfCataractLeftEye?: string;
  lensClarityLeftEye?: string;
  leftEyeFundusExamination?: string;
  rightEyeRefraction?: string;
  rightEyeSphericalPower?: string;
  rightEyeCylindricalPower?: string;
  rightEyeAxis?: string;
  rightEyeAdditionForReading?: string;
  leftEyeRefraction?: string;
  leftEyeSphericalPower?: string;
  leftEyeCylindricalPower?: string;
  leftEyeAxis?: string;
  leftEyeAdditionForReading?: string;
  rightEyeLensType?: string;
  rightEyeLensDiameter?: string;
  rightEyeBaseCurve?: string;
  leftEyeLensType?: string;
  leftEyeLensDiameter?: string;
  leftEyeBaseCurve?: string;
  frameType?: string;
  frameManufacturer?: string;
  frameModel?: string;
  frameSize?: string;
  frameLensWidth?: string;
  frameBridgeWidth?: string;
  frameTempleLength?: string;
  frameMaterial?: string;
  frameColor?: string;
  frameShape?: string;
  frameLensType?: string;
  frameLensIndex?: string;
  frameLensCoating?: string;
  frameLensUVProtection?: string;
  frameLensColor?: string;
  eyeglassesPrescription?: string;
  contactLensesPrescription?: string;
  additionalTreatments?: string;
  followUpInstructions?: string;
  generalNotes?: string;
  createdAt: string;
  updatedAt: string;
}
