import { z } from "zod";

const optionalString = z.string().or(z.literal("")).or(z.null()).optional();

export const examSchema = z.object({
  examDate: z.string().min(1),
  examType: optionalString,
  examStatus: z.enum(["pending", "completed", "cancelled"]),
  rightEyeWithoutCorrection: optionalString,
  rightEyeWithCorrection: optionalString,
  rightEyePressure: optionalString,
  leftEyeWithoutCorrection: optionalString,
  leftEyeWithCorrection: optionalString,
  leftEyePressure: optionalString,
  cornealShapeRightEye: optionalString,
  cornealSurfaceRightEye: optionalString,
  rightEyeRetinaExamination: optionalString,
  presenceOfCataractRightEye: optionalString,
  lensClarityRightEye: optionalString,
  rightEyeFundusExamination: optionalString,
  cornealShapeLeftEye: optionalString,
  cornealSurfaceLeftEye: optionalString,
  leftEyeRetinaExamination: optionalString,
  presenceOfCataractLeftEye: optionalString,
  lensClarityLeftEye: optionalString,
  leftEyeFundusExamination: optionalString,
  rightEyeRefraction: optionalString,
  rightEyeSphericalPower: optionalString,
  rightEyeCylindricalPower: optionalString,
  rightEyeAxis: optionalString,
  rightEyeAdditionForReading: optionalString,
  leftEyeRefraction: optionalString,
  leftEyeSphericalPower: optionalString,
  leftEyeCylindricalPower: optionalString,
  leftEyeAxis: optionalString,
  leftEyeAdditionForReading: optionalString,
  rightEyeLensType: optionalString,
  rightEyeLensDiameter: optionalString,
  rightEyeBaseCurve: optionalString,
  leftEyeLensType: optionalString,
  leftEyeLensDiameter: optionalString,
  leftEyeBaseCurve: optionalString,
  frameType: optionalString,
  frameManufacturer: optionalString,
  frameModel: optionalString,
  frameSize: optionalString,
  frameLensWidth: optionalString,
  frameBridgeWidth: optionalString,
  frameTempleLength: optionalString,
  frameMaterial: optionalString,
  frameColor: optionalString,
  frameShape: optionalString,
  frameLensType: optionalString,
  frameLensIndex: optionalString,
  frameLensCoating: optionalString,
  frameLensUVProtection: optionalString,
  frameLensColor: optionalString,
  eyeglassesPrescription: optionalString,
  contactLensesPrescription: optionalString,
  additionalTreatments: optionalString,
  followUpInstructions: optionalString,
  generalNotes: optionalString,
});

export type ExaminationFormValues = z.infer<typeof examSchema>;
